Repository influxdata/influxdb-client-csharp, pull requests merged in 2020-06, with the labels that each got.

#100 fix: thread-safety disposing of clients
  Client.Test/ItWriteApiRaceTest.cs
  Client.Test/WriteApiTest.cs
  Client/InfluxDBClient.cs
  Client/WriteApi.cs
Labels: bug

#96 feat: PointData Immutability
  Client.Core/Client.Core.csproj
  Client.Test/MeasurementMapperTest.cs
  Client.Test/PointDataTest.cs
  Client/Client.csproj
  Client/Internal/MeasurementMapper.cs
  Client/README.md
  Client/Writes/PointData.cs
Labels: enhancement

#103 feat: Removed log system from Bucket, Dashboard, Organization, Task and Users API
  CHANGELOG.md
  Client.Test/InfluxDbClientTest.cs
  Client.Test/ItBucketsApiTest.cs
  Client.Test/ItOrganizationsApiTest.cs
  Client.Test/ItUsersApiTest.cs
  Client/BucketsApi.cs
  Client/InfluxDB.Client.Api/Domain/BucketLinks.cs
  Client/InfluxDB.Client.Api/Domain/CloudUser.cs
  Client/InfluxDB.Client.Api/Domain/CloudUserLinks.cs
  Client/InfluxDB.Client.Api/Domain/DBRP.cs
  Client/InfluxDB.Client.Api/Domain/DashboardLinks.cs
  Client/InfluxDB.Client.Api/Domain/Invite.cs
  Client/InfluxDB.Client.Api/Domain/InviteLinks.cs
  Client/InfluxDB.Client.Api/Domain/Invites.cs
  Client/InfluxDB.Client.Api/Domain/InvitesLinks.cs
  Client/InfluxDB.Client.Api/Domain/OperationLog.cs
  Client/InfluxDB.Client.Api/Domain/OperationLogLinks.cs
  Client/InfluxDB.Client.Api/Domain/OperationLogs.cs
  Client/InfluxDB.Client.Api/Domain/OrganizationLinks.cs
  Client/InfluxDB.Client.Api/Domain/Query.cs
  Client/InfluxDB.Client.Api/Domain/ResourceMembers.cs
  Client/InfluxDB.Client.Api/Domain/ResourceOwners.cs
  Client/InfluxDB.Client.Api/Domain/RunLinks.cs
  Client/InfluxDB.Client.Api/Domain/Sources.cs
  Client/InfluxDB.Client.Api/Domain/UserLinks.cs
  Client/InfluxDB.Client.Api/Domain/Users.cs
  Client/InfluxDB.Client.Api/Domain/UsersLinks.cs
  Client/InfluxDB.Client.Api/Service/BucketsService.cs
  Client/InfluxDB.Client.Api/Service/CloudUsersService.cs
  Client/InfluxDB.Client.Api/Service/DBRPsService.cs
  Client/InfluxDB.Client.Api/Service/DashboardsService.cs
  Client/InfluxDB.Client.Api/Service/InvitesService.cs
  Client/InfluxDB.Client.Api/Service/OperationLogsService.cs
  Client/InfluxDB.Client.Api/Service/OrganizationsService.cs
  Client/InfluxDB.Client.Api/Service/SetupService.cs
  Client/InfluxDB.Client.Api/Service/UsersService.cs
  Client/OrganizationsApi.cs
  Client/UsersApi.cs
  Scripts/swagger.yml
Labels: api

#104 chore(ci): upgrade InfluxDB 1.7 to 1.8
  .circleci/config.yml
  CHANGELOG.md
  Scripts/influxdb-restart.sh
Labels: ci

#102 feat: Add async/await Write API without batching
  CHANGELOG.md
  Client.Test/ItWriteApiAsyncTest.cs
  Client/InfluxDBClient.cs
  Client/README.md
  Client/WriteApiAsync.cs
  Examples/RunExamples.cs
  Examples/WriteApiAsyncExample.cs
Labels: enhancement

#106 fix: serialization of `\n`, `\r` and `\t` to Line Protocol, `=` is valid sign for measurement name
  CHANGELOG.md
  Client.Test/PointDataTest.cs
  Client/Writes/PointData.cs
Labels: bug
