Repository influxdata/influxdb-client-csharp, pull requests merged in 2020-01, with the labels that each got.

#51 Update readme to use PointData class
  README.md
Labels: documentation

#56 fix: WriteApi is disposed after a buffer is fully processed
  CHANGELOG.md
  Client.Test/ItWriteQueryApiTest.cs
  Client.Test/WriteApiTest.cs
  Client/WriteApi.cs
Labels: bug

#57 feat(logging): LogLevel Header also contains query parameters
  CHANGELOG.md
  Client.Core/Internal/LoggingHandler.cs
  Client.Test/InfluxDbClientTest.cs
  Client.Test/ItWriteQueryApiTest.cs
Labels: enhancement

#58 chore(ci): build over dotnet 3.0, 3.1 and test on WindowsServer
  .circleci/config.yml
  CHANGELOG.md
  Client.Core.Test/AbstractTest.cs
  Client.Test/ItInfluxDBClientTest.cs
  Client.Test/ItTelegrafsApiTest.cs
  Scripts/ci-test.sh
  Scripts/influxdb-onboarding.sh
  Scripts/influxdb-restart.sh
Labels: enhancement

#60 chore(ci): deploy dev version into Nuget repository
  CHANGELOG.md
  Client.Core/Client.Core.csproj
  Client.Legacy/Client.Legacy.csproj
  Client/Client.csproj
  Examples/Examples.csproj
  Scripts/ci-deploy-snapshot.sh
Labels: enhancement
